### PR TITLE
Use light/dark based on user preferences

### PR DESCRIPTION
**Pull request by jdesrosiers**
Users that have their preferences set to prefer light mode will now get the Solarizaed Light theme rather than the Solarized Dark theme. There is no way to toggle between light and dark mode other than to change browser settings.

### CODE REVIEW

**Comment by jviotti** [comment]
The lack of `theme-color` makes it default to black on Safari (even on light theme on the Mac), but I think it's fine. Its not a big deal and doesn't look bad.

**Comment by jviotti** [comment]
I think there is something off with this functionality right now. At least for me on Safari, it flickers for a bit and then goes back to dark:

https://github.com/hyperjump-io/json-schema.hyperjump.io/assets/2192773/eb387186-a730-4ec6-8697-9d1ef839e9fd

**Comment by jdesrosiers** [comment]
@jviotti I think I solved the flicker as best is possible. Let me know if it works ok for you.

**Comment by jviotti** [comment]
@jdesrosiers Thanks a lot! Works great on Firefox, but not on Safari (it always stays dark there), but it is enough for my use case. I'll take the screenshots on Firefox.

**Pull request merged**
